name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test_cypress:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js version from .nvmrc
        run: |
          nvm install
          nvm use
        shell: bash

      - name: Install dependencies
        run: npm ci

      - name: Install Cypress
        run: npx cypress install

      - name: Run Cypress tests
        run: npx cypress run -b chrome
